export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";

export const ADD_NEW_SHIPPING_ADDRESS_REQUEST =
  "ADD_NEW_SHIPPING_ADDRESS_REQUEST";
export const ADD_NEW_SHIPPING_ADDRESS_SUCCESS =
  "ADD_NEW_SHIPPING_ADDRESS_SUCCESS";
export const ADD_NEW_SHIPPING_ADDRESS_FAIL = "ADD_NEW_SHIPPING_ADDRESS_FAIL";

export const SHIPPING_ADDRESS_UPDATE_REQUEST =
  "SHIPPING_ADDRESS_UPDATE_REQUEST";
export const SHIPPING_ADDRESS_UPDATE_SUCCESS =
  "SHIPPING_ADDRESS_UPDATE_SUCCESS";
export const SHIPPING_ADDRESS_UPDATE_FAIL = "SHIPPING_ADDRESS_UPDATE_FAIL";
